"""create table

Revision ID: 115c76ea3b36
Revises: 
Create Date: 2022-08-12 19:26:09.352440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115c76ea3b36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('token', sa.String(), nullable=True))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'token')
    op.drop_column('users', 'name')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
