"""create table

Revision ID: c9bd4a8b8568
Revises: 115c76ea3b36
Create Date: 2022-08-12 20:01:47.993883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bd4a8b8568'
down_revision = '115c76ea3b36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
